// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIqGjZlGYAImkf-r1duU2-b8-PBZ0lM8',
    appId: '1:1078866639012:web:4b2ac0b7a7a0505cc50e31',
    messagingSenderId: '1078866639012',
    projectId: 'hamsil-app',
    authDomain: 'hamsil-app.firebaseapp.com',
    storageBucket: 'hamsil-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9z_yebhrdS5FlzacYg3esR0lVyiJK0as',
    appId: '1:1078866639012:android:dc84922f21506946c50e31',
    messagingSenderId: '1078866639012',
    projectId: 'hamsil-app',
    storageBucket: 'hamsil-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoy5eaiBqB3eXaDpvJEL8dhlfRZqOI90I',
    appId: '1:1078866639012:ios:9f93a1785d20067ec50e31',
    messagingSenderId: '1078866639012',
    projectId: 'hamsil-app',
    storageBucket: 'hamsil-app.firebasestorage.app',
    iosBundleId: 'com.hamsil.app',
  );
}
